// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package calculator

import (
	"bytes"
	"context"
	"reflect"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

const BenefitOverTwoYears = 150
const BenefitOverFiveYears = 400
const BenefitOverTenYears = 1200
const TwoFamilyMembersBenefit = 20
const ThreeFamilyMembersBenefit = 40
const FourFamilyMembersBenefit = 60
const PositionBenefit = 100
const ExpenseDiscount = 0.03
const EmployerDiscount = 0.01

func init() {
}

